{% set name = "cuda-opencl" %}
{% set version = "12.4.127" %}
{% set lib_version = "1.0.0" %}
{% set cuda_version = "12.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_opencl/{{ platform }}/cuda_opencl-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 34648ff01acb49ec0247e4cb240470b93e9d0c9ee0641091a7bfee0698f09ed9  # [linux64]
  sha256: 4b5be4ad11ded8c33e83f757435a6c3fa5ff309339b13e18da9f520fb349bf3b  # [win]

build:
  number: 1
  skip: true  # [osx or aarch64 or ppc64le]

test:
  commands:
    - test -f $PREFIX/targets/{{ target_name }}/lib/libOpenCL.so.{{ lib_version }}                                                # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libOpenCL.so.{{ lib_version.split(".")[0] }}                                  # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libOpenCL.so.{{ lib_version.split(".")[0] }}.{{ lib_version.split(".")[1] }}  # [linux]
    - test -f $PREFIX/etc/OpenCL/vendors/cuda.icd                                                                                 # [linux]
    - if not exist %LIBRARY_PREFIX%\etc\OpenCL\vendors\cuda.icd exit 1                                                            # [win]

outputs:
  - name: cuda-opencl
    files:
      - targets/{{ target_name }}/lib/libOpenCL.so.*  # [linux]
      - etc/OpenCL/vendors/cuda.icd                   # [linux]
      - Library\etc\OpenCL\vendors\cuda.icd           # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
      host:
        - cuda-version {{ cuda_version }}
        - ocl-icd                    # [linux]
        - khronos-opencl-icd-loader  # [win]
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - ocl-icd                    # [linux]
        - khronos-opencl-icd-loader  # [win]
    # Tests are defined at the top level, due to package/output name conflicts.
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA OpenCL native Libraries
      description: |
        CUDA OpenCL native Libraries
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-opencl-dev
    build:
      run_exports:
        - {{ pin_subpackage("cuda-opencl", max_pin="x") }}
    files:
      - lib/pkgconfig                               # [linux]
      - targets/{{ target_name }}/include           # [linux]
      - targets/{{ target_name }}/lib/libOpenCL.so  # [linux]
      - Library\include                             # [win]
      - Library\lib                                 # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-opencl", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/pkgconfig/opencl-*.pc                   # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/CL/cl.h   # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libOpenCL.so  # [linux]
        - if not exist %LIBRARY_INC%\CL\cl.h exit 1                     # [win]
        - if not exist %LIBRARY_LIB%\OpenCL.lib exit 1                  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA OpenCL native Libraries
      description: |
        CUDA OpenCL native Libraries
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA OpenCL native Libraries
  description: |
    CUDA OpenCL native Libraries
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
